# Use the official Node.js image as the base image
FROM node:latest

# Create and change to the app directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY ./auth-api-ts/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY ./auth-api-ts .

RUN npm run build

ENV API_PORT=3000

# Expose the application port
EXPOSE ${API_PORT}

# Start the application
CMD ["npm", "run", "start"]