services:
  app:
    image: node:latest
    container_name: app
    working_dir: /usr/src/app/
    volumes:
      - ./auth-api-ts/:/usr/src/app
    networks:
      - mynetwork
    ports:
      - "8080:${API_PORT}"
    environment:
      - API_PORT=${API_PORT}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=db
      - DATABASE_PORT=${DATABASE_PORT}"
      - DATABASE_NAME=${DATABASE_NAME}
    command: sh -c "ls -la /usr/src/app"

networks:
  mynetwork:
    driver: bridge
