services:
  db:
    image: postgres:latest
    container_name: CI-CD-DB-Postgres
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ${PROJECT_ROOT}/db:/docker-entrypoint-initdb.d
    ports:
      - "5433:${DATABASE_PORT}"
    networks:
      - mynetwork

  app:
    image: node:latest
    container_name: app
    working_dir: /usr/src/app/
    volumes:
      - ${PROJECT_ROOT}:/usr/src/app
    
    depends_on:
      - db
    networks:
      - mynetwork
    ports:
      - "8080:${API_PORT}"
    environment:
      - API_PORT=${API_PORT}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=db
      - DATABASE_PORT=${DATABASE_PORT}"
      - DATABASE_NAME=${DATABASE_NAME}
    command: sh -c "cd db/ && ls -la"

networks:
  mynetwork:
    driver: bridge
