services:
  db:
    build:
      context: .. #This is the root of the project
      dockerfile: ./Docker/db/Dockerfile
    container_name: CI-CD-DB-Postgres
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mynetwork

  app:
    build:
      context: ..
      dockerfile: ./Docker/app/Dockerfile${ENVIRONMENT}
    container_name: app
    working_dir: /usr/src/app
    depends_on:
      - db
    networks:
      - mynetwork
    ports:
      - "${API_PORT}:${API_PORT}"
    environment:
      - API_PORT=${API_PORT}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=db
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}

volumes:
  pgdata:

networks:
  mynetwork:
    driver: bridge
