services:
  db:
    build:
      context: ..
      dockerfile: ./Docker/db/Dockerfile
    container_name: DB-Postgres-dev
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    volumes:
      - pgdata_dev:/var/lib/postgresql/data
    networks:
      - mynetwork_dev

  app:
    build:
      context: ..
      dockerfile: ./Docker/app/Dockerfile-dev
    container_name: app-dev
    working_dir: /usr/src/app
    depends_on:
      - db
    networks:
      - mynetwork_dev
    ports:
      - "${API_PORT}:${API_PORT}"
    environment:
      - API_PORT=${API_PORT}
      - BASE_APP_URL=http://localhost:${API_PORT}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=db
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
    volumes:
      - ../auth-api-ts:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  pgdata_dev:

networks:
  mynetwork_dev:
    driver: bridge