services:
  app:
    build:
      context: ..
      dockerfile: ./Docker/app/Dockerfile${ENVIRONMENT}
    container_name: app
    working_dir: /usr/src/app
    ports:
      - "${API_PORT}:${API_PORT}"
    environment:
      - API_PORT=${API_PORT}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=db
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
