services:
  db:
    image: postgres:latest
    container_name: CI-CD-DB-Postgres
    environment:
      POSTGRES_DB: auth-api-ci-cd
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
    networks:
      - mynetwork

  app:
    image: node:latest
    container_name: CI-CD-App
    working_dir: /usr/src/app
    volumes:
      - ./../auth-api-ts/:/usr/src/app
    depends_on:
      - db
    networks:
      - mynetwork
    ports:
      - "8080:3000"
    command: sh -c "npm install && npm run start:dev"

networks:
  mynetwork:
    driver: bridge