name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker:latest
      options: --privileged
    
    env:
      API_PORT: 3000
      DATABASE_PROVIDER: postgres
      DATABASE_HOST: db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: auth-api-ci-cd
      DATABASE_PORT: 5432

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
  
    - name: Verify Docker Installation
      working-directory: Docker
      run : |
        docker --version
        docker-compose --version

    - name: Set up Docker Compose
      working-directory: Docker
      run: |
        docker-compose up -d

    - name: Check Docker Compose services status
      working-directory: Docker
      run: docker-compose ps

    - name: Check Docker Compose logs
      working-directory: Docker
      run: docker-compose logs app
    
    - name: Check docker volume
      working-directory: Docker
      run: docker-compose exec app sh -c "ls -la /usr/src/app"
    
    - name: Check docker volume
      working-directory: Docker
      run: ls -la ./../

    - name: Check memory usage
      run: docker stats --no-stream

    - name: Check docker volume
      working-directory: Docker
      run: docker-compose exec app sh -c "ls"

    #- name: Install Dependencies
    #  working-directory: Docker
    #  run: docker-compose exec app sh -c "npm install"
    
    #- name: Run Linter
    #  working-directory: Docker
    #  run: docker-compose exec app sh -c "npm run lint"
    #  continue-on-error: true
      
    #- name: Run Unit Tests
    #  working-directory: Docker
    #  run: docker-compose exec app sh -c "npm run test:unit"

    #- name: Run Integration Tests
    #  working-directory: Docker
    #  run: docker-compose exec app sh -c "npm run test:e2e"
