name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker:latest
      options: --privileged
    
    env:
      API_PORT: 3000
      DATABASE_PROVIDER: postgres
      DATABASE_HOST: db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: auth-api-ci-cd
      DATABASE_PORT: 5432

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Verify Docker Installation
      run : |
        docker --version
        docker-compose --version

    - name: Set up Docker Compose
      run: |
        docker-compose up -d
      working-directory: Docker

    - name: Install Dependencies
      run: docker-compose exec app sh -c "npm install"
      working-directory: Docker
    
    - name: Run Linter
      run: docker-compose exec app sh -c "npm run lint"
      working-directory: Docker
      continue-on-error: true
      
    - name: Run Unit Tests
      run: docker-compose exec app sh -c "npm run test:unit"
      working-directory: Docker

    - name: Run Integration Tests
      run: docker-compose exec app sh -c "npm run test:e2e"
      working-directory: Docker