name: CI/CD

on: [push]

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    container:
      image: docker:latest
      options: --privileged
    
    env:
      API_PORT: 3000
      DATABASE_PROVIDER: postgres
      DATABASE_HOST: db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: auth-api-ci-cd
      DATABASE_PORT: 5432
      ENVIRONMENT: -dev

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
  
    - name: Verify Docker Installation
      run : |
        docker --version
        docker-compose --version

    - name: Build docker image
      working-directory: Docker
      run: |
       docker-compose -f docker-compose.yml build
    
    - name: Build docker image
      working-directory: Docker
      run: |
       docker-compose -f docker-compose.yml up -d
    
    - name: Run Linter
      working-directory: Docker
      run: docker-compose exec app sh -c "npm run lint"
      continue-on-error: true
      
    - name: Run Unit Tests
      working-directory: Docker
      run: docker-compose exec app sh -c "npm run test:unit"

    - name: Run Integration Tests
      working-directory: Docker
      run: docker-compose exec app sh -c "npm run test:e2e"

  build:
    runs-on: ubuntu-latest
    needs: lint_and_test
    container:
      image: docker:latest
      options: --privileged
    
    env:
      API_PORT: 3000
      DATABASE_PROVIDER: postgres
      DATABASE_HOST: db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: auth-api-ci-cd
      DATABASE_PORT: 5432
      ENVIRONMENT: -build

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
  
    - name: Verify Docker Installation
      run : |
        docker --version
        docker-compose --version

    - name: Build docker image
      working-directory: Docker
      run: |
       docker-compose -f docker-compose.yml build
    
    - name: Build docker image
      working-directory: Docker
      run: |
       docker-compose -f docker-compose.yml up -d

  deploy:
    runs-on: ubuntu-latest
    needs: build
    container:
      image: docker:latest
      options: --privileged
    
    env:
      API_PORT: 3000
      DATABASE_PROVIDER: postgres
      DATABASE_HOST: db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: auth-api-ci-cd
      DATABASE_PORT: 5432
      ENVIRONMENT: -build

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
  
    - name: Verify Docker Installation
      run : |
        docker --version
        docker-compose --version

    - name: Build docker image (in the future create a real deploy job)
      working-directory: Docker
      run: |
       docker-compose -f docker-compose-deploy.yml build
    
    - name: Build docker image
      working-directory: Docker
      run: |
       docker-compose -f docker-compose-deploy.yml up -d
