name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker:latest
      options: --privileged
    
    env:
      API_PORT: 3000
      DATABASE_PROVIDER: postgres
      DATABASE_HOST: db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: auth-api-ci-cd
      DATABASE_PORT: 5432

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
  
    - name: Verify Docker Installation
      run : |
        docker --version
        docker-compose --version

    - name: Build docker image
      working-directory: Docker
      run: |
       docker-compose build
    
    - name: Build docker image
      working-directory: Docker
      run: |
       docker-compose up -d
    
    - name: Run Linter
      working-directory: Docker
      run: docker-compose exec app sh -c "npm run lint"
      continue-on-error: true
      
    - name: Run Unit Tests
      working-directory: Docker
      run: docker-compose exec app sh -c "npm run test:unit"

    - name: Run Integration Tests
      working-directory: Docker
      run: docker-compose exec app sh -c "npm run test:e2e"
